### ISSUE TITLE
Looking forward - Cain VZEdit

### ISSUE THREAD

**Issue by StigLau** [pete-cain/VZEdit#3]
I've looked around for a VZ-1 patch-editor, and it is the closest I've come to yet concerning form/function/deployment.
However, the JAZZ midi plugin is based on is dead, in the way its used. I have gone back and forth to find a combination of an old chrome browser and compatible jazz browser plugin, and I would recommend noone to try this too.

I am personally looking at a workaround, using SysEx Librarian for backups and uploading other peoples patches, and Cain VZEdit for viewing the patch settings. 

However, I believe this project can fairly easily be moved into working condition by changing the Jazz dependency and moving to Webmidi + sysex, as well as converting long values to hex. 

I am in the slow process of trying to perform such a shift, but I would like to hear the thoughts from the project owner on the subject. -Webmidi or a different library?
Regards
 -Stig,

**Comment by pete-cain** [comment]
Hi Stig,

thank you for reaching out to me.

It is an awfull project, which I created while learning js but 
nevertheless I hope it is somehow comprehendible.

Yes, the move to Webmidi is the most logical and promising step, I 
totally agree. I even moved forward into that direction, but got caught 
by the fact, that in that case it is necessary to have it hosted on an 
HTTPS (secure) site due to the sysex data. In my case I would have to 
pay extra fees to get the certificate from my provider, which I am 
currently not willing to do.

If you can get it to work with the Webmidi API - which looks like it 
should be doable - and find a way to host it, then I would be more than 
glad.

Very kind regards,

Pete

Am 26.10.2020 um 22:13 schrieb Stig Lau:

**Comment by StigLau** [comment]
Agreed.

On hosting
-----------
I'm not a frontendev myself, though my goto cost-sensitive ssl approach would be cloudflare.com if you want to keep on hosting yourself or https://pages.github.com as a fully hosted alternative connected to your github project. Note that your project runs directly from HTML + .js + webmidi directly from localhost/disk, requiring only clicking "accept" on a popup when refreshing, for dev purposes. 

Inspiration
--------------
https://oscillatorsink.github.io has excellent synth-related Youtube content and developed, amongst other things, a couple of webmidi synth editors; https://synthmata.com/volca-fm running from https://github.com/synthmata/synthmata.github.io 

Commitment
-------------
I'm not interested in owning/long term maintaining more projects than I already AM. That said, your project seems fairly appropriate, and during the current plague, I might have enough on my hands to at least get something working on webmidi, and hopefully lift the project in a fashion that can enable to deliver value to VZ-1 owners in the future requiring minimal effort.

Way forward
-------------
Can you have a look at synthmata/volca-fm and evaluate from your perspective, what matches your vision of this project? Aligning some of synthmatas approach on webmidi ports ok to VZEdit and I believe I can get that working. I'm forking this project when I get a couple of steps forward, and hopefully reach a functional PR replacement.

Regards
 -Stig,

**Comment by pete-cain** [comment]
Hi Stig, thank you for your tips and support.
It should at least be in a working state at https://pete-cain.github.io/VZEdit/
